// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfuTIEve9XAkbw7vy4s6KzijAhX1fmR8',
    appId: '1:472098888256:web:0e86f630ec9626763f9da5',
    messagingSenderId: '472098888256',
    projectId: 'nearby-finder-app-2205b',
    authDomain: 'nearby-finder-app-2205b.firebaseapp.com',
    storageBucket: 'nearby-finder-app-2205b.firebasestorage.app',
    measurementId: 'G-6BTJGGSRGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbuX-smjI5Se_YaC0RcqxNCDiEoIGDlQ',
    appId: '1:472098888256:android:7bc33de732d762d73f9da5',
    messagingSenderId: '472098888256',
    projectId: 'nearby-finder-app-2205b',
    storageBucket: 'nearby-finder-app-2205b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCArnLbTXFRybMzhL64t296aVJSjNMGlfg',
    appId: '1:472098888256:ios:4ca52d6fb182d18b3f9da5',
    messagingSenderId: '472098888256',
    projectId: 'nearby-finder-app-2205b',
    storageBucket: 'nearby-finder-app-2205b.firebasestorage.app',
    iosBundleId: 'com.example.nearbyFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCArnLbTXFRybMzhL64t296aVJSjNMGlfg',
    appId: '1:472098888256:ios:4ca52d6fb182d18b3f9da5',
    messagingSenderId: '472098888256',
    projectId: 'nearby-finder-app-2205b',
    storageBucket: 'nearby-finder-app-2205b.firebasestorage.app',
    iosBundleId: 'com.example.nearbyFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnfuTIEve9XAkbw7vy4s6KzijAhX1fmR8',
    appId: '1:472098888256:web:3c2c229bae5dbc853f9da5',
    messagingSenderId: '472098888256',
    projectId: 'nearby-finder-app-2205b',
    authDomain: 'nearby-finder-app-2205b.firebaseapp.com',
    storageBucket: 'nearby-finder-app-2205b.firebasestorage.app',
    measurementId: 'G-E43CJPSRV5',
  );

}